TRUNCATE TABLE announcement;
TRUNCATE TABLE announcement_user;
TRUNCATE TABLE application;
TRUNCATE TABLE application_history_log;
TRUNCATE TABLE application_notification;
TRUNCATE TABLE application_notification_client;
TRUNCATE TABLE application_notification_event;
TRUNCATE TABLE application_notification_state;
TRUNCATE TABLE application_option;
TRUNCATE TABLE client;
TRUNCATE TABLE client_auth;
TRUNCATE TABLE client_events;
TRUNCATE TABLE contact_message;
TRUNCATE TABLE discount;
TRUNCATE TABLE discount_membership;
-- TRUNCATE TABLE email;
TRUNCATE TABLE event;
TRUNCATE TABLE event_album;
TRUNCATE TABLE event_album_size;
TRUNCATE TABLE event_auth;
TRUNCATE TABLE event_photo;
TRUNCATE TABLE event_photo_comment;
TRUNCATE TABLE event_photo_comment_client;
TRUNCATE TABLE event_photo_comment_user;
TRUNCATE TABLE event_photo_rate;
TRUNCATE TABLE event_photo_size;
-- TRUNCATE TABLE faq;
TRUNCATE TABLE log;
TRUNCATE TABLE membership;
TRUNCATE TABLE meta;
TRUNCATE TABLE notification;
TRUNCATE TABLE notification_user;
-- TRUNCATE TABLE `option`;
-- TRUNCATE TABLE option_group;
-- TRUNCATE TABLE option_image;
-- TRUNCATE TABLE option_type;
-- TRUNCATE TABLE page;
TRUNCATE TABLE photo_size;
TRUNCATE TABLE portfolio;
TRUNCATE TABLE portfolio_album;
TRUNCATE TABLE portfolio_photo;
TRUNCATE TABLE studio;
TRUNCATE TABLE studio_link;
TRUNCATE TABLE studio_message;
TRUNCATE TABLE studio_person;
TRUNCATE TABLE ticket;
TRUNCATE TABLE ticket_reply;
-- TRUNCATE TABLE translation;
-- TRUNCATE TABLE translation_category;
-- TRUNCATE TABLE translation_source;
-- TRUNCATE TABLE user;
TRUNCATE TABLE user_option;
TRUNCATE TABLE user_order;
TRUNCATE TABLE user_order_photo;
TRUNCATE TABLE user_subscription;